server:
   port: 8888
   contextPath: /shoppingmall 
   
   error:
      whitelabel:
            enabled: false
       
spring:
   profiles:
      active: dev
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.1.52:3307/shoppingmall?allowMultiQueries=true
      username: shoppingmall
      password: shoppingmall   
   devtools: 
      livereload:
         enabled: true
   http:  
      encoding:
         charset: UTF-8
         enabled: true
         forced: true
         forced-request: true
         forced-response: true
   aop:
      auto: true
   aop-proxy-target-class: true
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 50MB
         
   zipkin:   
      baseUrl: http://192.168.1.52:9411/     
   application:
      name: shoppingmall-backend
   sleuth:
      enabled: true
      sampler:
         probability: 1.0          

mybatis:
   config-location: classpath:mybatis/configuration.xml
   
security:
         user:
              name: test
              password: 5678
#         oauth2:
#                client:
#                       client-id: pjmall
#                       client-secret: 1234 



